### PR TITLE
missing hostname in logs

### PR DESCRIPTION
**Pull request by M4tteoP**
Hi there,
taking a look at https://github.com/corazawaf/coraza/issues/515, indeed `resolvedIP` variable is never populated.
To my eyes seems that the right value could be the `ServerIPAddress`, populated at the beginning of the transaction, when `ProcessConnection` is called:
https://github.com/corazawaf/coraza/blob/bffb4359d11967e9d13c7ec67a35868b1553ad1e/internal/corazawaf/transaction.go#L638

Still, taking a look at the [connector](https://github.com/corazawaf/coraza-spoa/blob/main/internal/request.go#L142), this fix would just populate the field with the IP and may not be useful for @mac-chaffee usecase.
If it sounds reasonable I can, as proposed, catch the `Host` header adding it to a new `tx.variables`, but I'm wondering about sanitizing the retrieved value 🤔.

Attempt to close https://github.com/corazawaf/coraza/issues/515.

### CODE REVIEW

**Comment by mac-chaffee** [comment]
It does look like modsecurity sets that badly-named "hostname" variable to an IP address: https://github.com/SpiderLabs/ModSecurity/blob/4127c1bf52d2b30a5c2c3e641b8085fd9a720f43/src/rule_message.cc#L45

Now that I think of it, I normally find out the real hostname by looking at the modsecurity audit logs which includes the full HTTP request that triggered the rule. Doesn't seem like that kind of audit logging exists in Coraza yet, so I do like the idea of an extra section in the existing logs in the meantime.

I'm not too worried about sanitization since Coraza is designed to log attack attempts anyway.

**Comment by jcchavezs** [comment]
@jptosso @fzipi could you chime in?

**Comment by fzipi** [comment]
@mac-chaffee Depends on the tool you are using to look at logs. I would say we should sanitize it before sending it out to a filesystem/tool. More information [here](https://cwe.mitre.org/data/definitions/117.html).

**Comment by fzipi** [comment]
I think that `resolveIP` was meant to get the actual name from the [ServerIPAddress()](https://github.com/corazawaf/coraza/blob/9d003ed52753367b75383566ca69bc3d467cc8a0/internal/corazarules/rule_match.go#L104). I don't know if we want to do an extra name resolution before logging, but if someone needs it we might use a config parameter like `HostnameLookups Off` from Apache.

So the quick solution is to use the `ServerIPAddress` for the resolveIP (probably adding a comment also), and in the future we can add configurable reverse resolution if needed.

**Review by fzipi — APPROVED** [review]
I think we can merge this one and create a follow up ticket.

**Comment by M4tteoP** [comment]
FYI, related conversation ModSecurity side: https://github.com/SpiderLabs/ModSecurity/pull/2906

**Pull request merged**
