### PR TITLE
Update tool versions

### PR DESCRIPTION
**Pull request by anuraaga**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**

- [ ] My code includes positive and negative tests.
- [ ] I have an appropriate description with correct grammar.
- [ ] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [ ] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Comment by anuraaga** [comment]
Hmm - looks like we're in a world where it's not possible to run lint in a way that works with both Go 1.18 and 1.20...

**Comment by jptosso** [comment]
I tried the same a few weeks ago and it failed hard, I had to rollback go. We should wait for more stability?

**Comment by anuraaga** [comment]
Unfortunately we can't control what version of Go is being used by a code author. I was able to set up both versiosn for pre/post 1.20

**Comment by anuraaga** [comment]
Ping @jcchavezs @jptosso

**Review by jcchavezs — APPROVED** [review]

**Pull request merged**
