### PR TITLE
fix audit filesizes audit bug

### PR DESCRIPTION
**Pull request by jptosso**
We expected the files sizes to be an array of sizes with consistent index FILENAME:FILESIZE, but it's a map of filenames->sizes.

Also standard transaction POST tests were transformed to multipart so we can address this.

### CODE REVIEW

**Comment by jptosso** [comment]
FILES_SIZES:a.txt size is 17, but we store it as 19, maybe we are also counting the size of CRLF?

**Comment by jptosso** [comment]
The performance regression is expected, as the new test is multipart, it used to be urlencoded

**Comment by anuraaga** [comment]
This seems similar to the fix in #399, should I remove it from that? That PR is pending on a question still

**Comment by jptosso** [comment]
Yes please, this is more specific to the bug fix. Although I might rollback the tests and create a new test for multipart

**Comment by anuraaga** [comment]
Feel free to take the simple test from that one

**Comment by anuraaga** [comment]
Oops I force pushed it 

TextTxMultipart
```


	al := tx.AuditLog()
	files := al.Transaction.Request.Files
	if len(files) == 0 {
		t.Error("Files not logged")
	}
	if files[0].Name != "a.html" {
		t.Errorf("Invalid file name: %s", files[0].Name)
	}
	if files[0].Size != 50 {
		t.Errorf("Invalid file size: %d", files[0].Size)
	}
```

**Comment by jcchavezs** [comment]
LGTM

**Review by anuraaga — APPROVED** [review]

**Pull request merged**
