### PR TITLE
add logger interface

### PR DESCRIPTION
**Pull request by zc2638**
This PR attempts to support https://github.com/corazawaf/coraza/issues/244

### CODE REVIEW

**Comment by fzipi** [comment]
Hi @zc2638 !

Thanks for your contribution! :)

One thing that I'm seeing with this PR is that we are moving away from doing zap directly to encapsulating logging in a new module. I see the value of this, so it's easier to change loggers afterwards.

But then from the zap perspective we are losing two things: we lose typing, which gives us additional context and safety,  and we move to a sugared logging that has performance implications.

Can you provide benchmarking on what are the benefits here for those two cases?

Thanks!

**Comment by fzipi** [comment]
Awesome, thanks for taking the time to explain it here. We were discussing about Logging in general and probably we need to refactor logging so we have.

Let's wait for @jptosso to chime in, but if this is only for the `DebugLog`, then performance is not strictly preferred over good abstractions.

**Comment by jptosso** [comment]
We are moving this conversation to https://github.com/corazawaf/coraza/issues/246, feel free to join the Wednesday meeting to discuss this

**Comment by zc2638** [comment]
> We are moving this conversation to #246, feel free to join the Wednesday meeting to discuss this

OK, what time does it start, where is the meeting address, I can't find it in the repo README.

**Comment by jptosso** [comment]
> > We are moving this conversation to #246, feel free to join the Wednesday meeting to discuss this
> 
> OK, what time does it start, where is the meeting address, I can't find it in the repo README.

There are instructions to join and the schedule: https://github.com/corazawaf/coraza/issues/247

Hope to see you there!

**Comment by jptosso** [comment]
Implemented in v3 branch

**Pull request closed without merging**
