### PR TITLE
chore: consolidate registering operators

### PR DESCRIPTION
**Pull request by fzipi**
## what

- consolidate initialization of operators in one file

## why

- coherency: transformations, actions, etc. use the same pattern

### CODE REVIEW

**Comment by fzipi** [comment]
So then the pattern to follow is the other way around? Can you follow up with a PR on what you need for consistency?

**Comment by fzipi** [comment]
@anuraaga BTW, is this knowledge documented somewhere?

**Comment by fzipi** [comment]
I wasn't saying your comments were annoying. And of course, I never implied _you_ were annoying. Never did, and never will, with any contributor in any of the projects I've been and will be.

I was saying, for the sake of others that will do work in this next, if those design decisions can be documented somewhere where they can be found.

You did take the approach you did, and it was totally fine... but others didn't knew. That's what I said.

**Comment by anuraaga** [comment]
If it wasn't annoying that's good - I get a bit anxious leaving comments since I've been on projects where other members blocked progress without actually contributing, making problems. The reality is I haven't had much time or enthusiasm for the project to be able to contribute meaningfully so it's time to step away. It's good to see some development happening again so will be nice to see what comes.

**Comment by jcchavezs** [comment]
@anuraaga it is sad to see you leave but your outstanding contributions will keep you in the core of coraza. I hope to cross paths soon as working with you was amazing.

**Pull request closed without merging**
