### PR TITLE
Update parser.go to fix path error

### PR DESCRIPTION
**Pull request by k4n5ha0**
like https://github.com/golang/go/issues/30616
filepath.Join will have bug on windows
path.Join will be fine

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**

- [ ] My code includes positive and negative tests.
- [ ] I have an appropriate description with correct grammar.
- [ ] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [ ] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks for coming by @k4n5ha0,

Is this truly a bug? We currently don't support windows but what I would
like to see here is a job enabled on windows and a failing test otherwise
we cannot trust the fix.

José Carlos Chávez


fre. 5. apr. 2024 kl. 03:46 skrev k4n5ha0 ***@***.***>:

**Comment by jptosso** [comment]
I agree with @jcchavezs; there is no support for Windows, and it might imply the refactoring of multiple components. For example, in some places, we point tests straight into /dev/null
If we are going to support windows, we require a new github action build for Windows, and a feature request

**Comment by k4n5ha0** [comment]
@jcchavezs @jptosso  hi，I am a web security engineer, mainly working on Windows devices. I mainly research vulnerability attack and defense techniques, but I am not very familiar with the development level GitHub pipeline. If the development goal does not include Windows, please ignore this PR. Thank you

**Comment by jcchavezs** [comment]
It does not include windows as of now mainly because we don't know windows users. If you know any we are up to support it.

**Pull request closed without merging**
