### PR TITLE
chore: drops dependabot

### PR DESCRIPTION
**Pull request by jcchavezs**
We have security updates enabled for the repository (which does not require dependabot), we don't need other updates as we should be conservative dealing with deps. See https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**

- [ ] My code includes positive and negative tests.
- [ ] I have an appropriate description with correct grammar.
- [ ] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [ ] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Comment by jptosso** [comment]
Instead of dropping dependabot we could limit the libraries it monitor to a core list and it's recursive dependencies. That list is documented under go.mod:
- libinjection-go (owned by us)
- aho-corasick (not mainteined)
- gjson
- binaryregexp

**Comment by jcchavezs** [comment]
I believe `golang.org/x/net` should be also considered e.g. because of https://github.com/golang/net/commit/63727cc58253c59c71cf8491bb4d7448990d63b8

**Comment by jcchavezs** [comment]
I'd still drop it. Even if we consider the right dependencies, dependabot PRs are usually red.

**Comment by jptosso** [comment]
Are we dropping this PR?

**Pull request closed without merging**
