### PR TITLE
feat(ci): enforce conventional commits title in prs

### PR DESCRIPTION
**Pull request by fzipi**
- enforce usage of conventional commits syntax on pr titles

### CODE REVIEW

**Comment by jptosso** [comment]
:(

**Comment by jcchavezs** [comment]
I think this is a great idea as long as it only applies to PR titles. I also think we should get some other opinions with a +1/-1 cc @M4tteoP @anuraaga @piyushroshan

**Comment by jptosso** [comment]
Are we doing this?

**Comment by fzipi** [comment]
I thought it was a good idea. But looks like @jptosso don't like same as @anuraaga. Care to explain why?

**Comment by anuraaga** [comment]
I find it adds extra burden to contributors with questionable value. Just my opinion so voted that way but wouldn't block a different decision.

**Comment by jcchavezs** [comment]
I agree with @anuraaga on the contributions friction. More so I think it is responsibility on the merger (coraza team) to make the merge commit title (usually the PRs title) meaningful and why not semantic. Changed my vote to -1.

**Pull request closed without merging**
