### PR TITLE
Use struct instead of slice for byte range validation (#305)

### PR DESCRIPTION
**Pull request by anuraaga**
Co-authored-by: Juan Pablo Tosso <jptosso@gmail.com>

v2 version of #305 

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [X] My code includes positive and negative tests.
- [X] I have an appropriate description with correct grammar.
- [X] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Review by jptosso — APPROVED** [review]
LGTM, thank you !

**Comment by jcchavezs** [comment]
I think go mod tidy might help.

**Comment by jcchavezs** [comment]
Is this something we can retry?

**Comment by anuraaga** [comment]
@jcchavezs Passed now

**Review by fzipi — APPROVED** [review]
Very nice indeed. Thanks!

**Pull request merged**
