### PR TITLE
Revert "tests: use assert library for tests"

### PR DESCRIPTION
**Pull request by jcchavezs**
Reverts corazawaf/coraza#298 as agreed in https://github.com/corazawaf/coraza/pull/298#issuecomment-1207895386

Ping @anuraaga

### CODE REVIEW

**Comment by anuraaga** [comment]
Thanks @jcchavezs sorry about this

**Comment by jcchavezs** [comment]
I will get this merged today so we can finally rebase v3/dev on top of this.

**Comment by jptosso** [comment]
@jcchavezs please fix lint issues so we can approve

**Comment by jptosso** [comment]
JC, maybe we could skip this, as tinygo support won't reach v2

**Comment by jcchavezs** [comment]
Once this gets merged I will port some test changes like all the `t.Run` introduced in this PR https://github.com/corazawaf/coraza/pull/298/files#diff-70802fcd97ffda50ed3469a4b405b7e4f399592753c208d4c054330b053a9946R79

**Review by jptosso — APPROVED** [review]

**Review by fzipi — APPROVED** [review]

**Pull request merged**
