### PR TITLE
fix: default actions for phase 2 are now hardcoded #191

### PR DESCRIPTION
**Pull request by jptosso**
According to #191 report, the secdefault actions for phase 2 are `phase:2,log,auditlog,pass` by default. This PR includes a mechanism to hardcode default actions.

TODO: We must add some logic to avoid repeated default actions, for example, if you use some default actions multiple time you would just concatenate actions:

```
SecDefaultActions "phase:2,log,auditlog,pass"
SecDefaultActions "phase:2,nolog,noauditlog,deny"
```
The previous statement would create the following rule:
```
SecAction "id:1,phase:2"
# compiles into: SecAction "id:1,phase:2,log,auditlog,pass,nolog,noauditlog,deny"
```

Should we fix that behavior in this PR ?

We should update ```ParseDefaultActions``` and set the following rules:
```
Replacements, action X replaces > action Y:
nolog > log
log > nolog
auditlog > noauditlog
noauditlog > auditlog

A disruptive action replaces all previous disruptive actions

no actions should repeat, except:
setvar
ctl
t
```

### CODE REVIEW

**Comment by fzipi** [comment]
One of the funny things in MS is that you can have default actions per _phase_.

**Comment by fzipi** [comment]
@jptosso There is a conflict now? Did you thought about the const?

**Review by fzipi — APPROVED** [review]
❤️ that const 😃

**Review by bxlxx — APPROVED** [review]
LGTM

**Pull request merged**
