### PR TITLE
feat: add reverse transformation support

### PR DESCRIPTION
**Pull request by jptosso**
I found this interesting use case, when payloads are being reversed to avoid detection. `t:reverse` will help to detect them.

### CODE REVIEW

**Comment by jcchavezs** [comment]
LGTM.

**Comment by jcchavezs** [comment]
Could you link any documentation where this is being used or requested?

**Comment by fzipi** [comment]
@jptosso Can this be documented somewhere? Looks like this is now in code only, and this is a new transformation that is not available "upstream".

An issue will also help others determine the use case and if matches their needs.

**Comment by fzipi** [comment]
@jptosso ping

**Pull request closed without merging**
