### PR TITLE
Separate out bodyprocessor implementations for TinyGo

### PR DESCRIPTION
**Pull request by anuraaga**
This splits out the bodyprocessor change from #254 to make it easier to review, especially since it introduces a new dependency.

JSON processing is tweaked to only use `encoding/json` (based on reflection) with gjson (not reflection since only supports decoding of `map`). The change is conservative to not change the normal path, but we could consider only using `gjson` for both paths in the future since it probably has better performance (their benchmarks show 2x better)

XML processing is tweaked to be disabled on TinyGo, we will look at how to make it work there in the future.

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [X] My code includes positive and negative tests.
- [X] I have an appropriate description with correct grammar.
- [X] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Comment by jcchavezs** [comment]
Using gjson for the sake of maintainability + performance is a good call
IMHO. What do you think @jptosso @fzipitria?

**Review by jptosso — APPROVED** [review]
LGTM, we are actually looking for a global replacement for encoding/json, as we do not need reflection, we should just parse everything as string

**Comment by anuraaga** [comment]
Sorry, fixed the tinygo test

**Comment by jptosso** [comment]
Sorry, I failed to fix conflicts, could you run a go mod tidy to fix the files?

**Comment by anuraaga** [comment]
Thanks @jptosso merged

**Pull request merged**
