### PR TITLE
chore: update go version

### PR DESCRIPTION
**Pull request by jptosso**
We support the latest 2 go versions, right now 1.19 and 1.20 https://tip.golang.org/doc/go1.20

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
BTW, while Go only supports two releases, I've seen many libraries support three to give some more time for upgrades, for example gRPC

https://github.com/grpc/grpc-go#prerequisites

Perhaps we should change to support three major versions too?

**Comment by jcchavezs** [comment]
> Perhaps we should change to support three major versions too?

I am in with this cc @jptosso

**Comment by jptosso** [comment]
@anuraaga @jcchavezs are we keeping 1.19+ compatibility?

**Comment by anuraaga** [comment]
I would suggest 1.18+

**Pull request closed without merging**
