### PR TITLE
fix for #176

### PR DESCRIPTION
**Pull request by bxlxx**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Comment by fzipi** [comment]
@jptosso My question now is: was there any reason for this to be forced lower case?

**Comment by bxlxx** [comment]
> @jptosso My question now is: was there any reason for this to be forced lower case?

I think some places are case insensitive, such as header configuration, but args configuration is case sensitive

**Comment by fzipi** [comment]
And the main question now is: what the RFC says about this?

**Comment by jptosso** [comment]
https://www.rfc-editor.org/rfc/rfc7230#page-19
> The scheme and host are case-insensitive and normally provided in lowercase; all other components are compared in a case-sensitive manner

It's case sensitive according to the RFC but I think we must make it lower case to avoid bypasses.

I think the only thing I would edit to fix this issue is the cookie processor under tx.AddRequestHeader.

**Comment by bxlxx** [comment]
> https://www.rfc-editor.org/rfc/rfc7230#page-19
> 
> > The scheme and host are case-insensitive and normally provided in lowercase; all other components are compared in a case-sensitive manner
> 
> It's case sensitive according to the RFC but I think we must make it lower case to avoid bypasses.
> 
> I think the only thing I would edit to fix this issue is the cookie processor under tx.AddRequestHeader.

I removed the problem of argument case-sensitive, and we will discuss this problem later.

**Review by jptosso — APPROVED** [review]
LGTM

**Review by fzipi — APPROVED** [review]
LGTM

**Pull request merged**
