### PR TITLE
Use standard library for base64 decode

### PR DESCRIPTION
**Pull request by anuraaga**
I noticed our base64Decode transformation allows mixed content in raw, but that is actually the `base64DecodeExt` transformation AFAICT

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#base64decodeext

I think we should go ahead and simplify the implementation of base64Decode for now (CRS tests still pass), and reintroduce the code for implementing base64DecodeExt in the future

### CODE REVIEW

**Comment by jcchavezs** [comment]
Sounds very reasonable to me, any thoughts @jptosso ?

**Comment by jptosso** [comment]
We tried this last year but it was failing some modsecurity tests regarding "malformed base64". But I would prefer to simplify this, this is unmaintainable code.

**Comment by anuraaga** [comment]
@jptosso Do you remember which tests? It seems to not affect our currently run ones. Maybe those were actually base64DecodeExt?

**Comment by jptosso** [comment]
https://github.com/SpiderLabs/secrules-language-tests/blob/a3d4405e5a2c90488c387e589c5534974575e35b/transformations/base64Decode.json

It's not failing anymore. You have my lgtm

**Review by jptosso — APPROVED** [review]

**Pull request merged**
