### PR TITLE
fix(@rx): add @rx captured data into Tx variable

### PR DESCRIPTION
**Pull request by bxlxx**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Review by fzipi — COMMENTED** [review]
I'm afk now, but:
- take a look at the new CRS rule 942130, there are capture examples there also
- we are capturing 0 till 9, right?

**Comment by bxlxx** [comment]
> I'm afk now, but:
> 
> * take a look at the new CRS rule 942130, there are capture examples there also
> * we are capturing 0 till 9, right?

Sure! I only fix the problem of capturing errors. We will copy 10 captures to variables when on a successful pattern match. The TX.0 variable always contains the entire area that the regular expression matched. All the other variables contain the captured values, in the order in which the capturing parentheses appear in the regular expression.

**Comment by fzipi** [comment]
@bxlxx Can you rebase so we get this one merged?

**Comment by fzipi** [comment]
@bxlxx Can you rebase so we get this one merged?

**Review by fzipi — APPROVED** [review]

**Review by jptosso — APPROVED** [review]
LGTM, I was wrong about the TX:0 for RX

**Pull request merged**
