### PR TITLE
Fix 209: Case sensitive evaluation

### PR DESCRIPTION
**Pull request by piyushroshan**
Fix case-sensitive rule evaluations.
Tested them to be compatible with Modsecurity behavior.

This PR introduces a new variable AnchoredVar that preserves the case-sensitive key with the value.
This is how we retain the original case to reflect in the MatchedVar* variables.

Ran minor performance benchmarks and found this PR made it better.

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Review by fzipi — CHANGES_REQUESTED** [review]
Hi @piyushroshan, thank you for this PR.

I see the need for the new AnchoredVar, but: do we need to export all fields in that type? If yes, then why the getters? Also, if you want to keep the getters,  per https://go.dev/doc/effective_go#Getters, can you remove the `Get` prefix? (which will make you rethink if you want them to be exported)

**Comment by piyushroshan** [comment]
> Hi @piyushroshan, thank you for this PR.
> 
> I see the need for the new AnchoredVar, but: do we need to export all fields in that type? If yes, then why the getters? Also, if you want to keep the getters, per https://go.dev/doc/effective_go#Getters, can you remove the `Get` prefix? (which will make you rethink if you want them to be exported)

Removed the Getter/Setter

**Review by fzipi — APPROVED** [review]
LGTM now.

**Review by jptosso — APPROVED** [review]
LGTM

**Pull request merged**
