### PR TITLE
Skips Evaluate during ProcessLogging if EngineOff

### PR DESCRIPTION
**Pull request by M4tteoP**
Closes https://github.com/corazawaf/coraza/issues/520.

When the rule engine is off, `tx.WAF.Rules.Eval` is still called during `ProcessLogging()`. It may end up with errors because of variables not initialized by previous rules (see https://github.com/corazawaf/coraza/issues/520).
This PR proposes to skill the rule evaluation but still process audit logs. I see value in this example scenario:
1. RuleEngine is `On`
2. A whitelist rule is triggered with `ctl:ruleEngine=Off`
3. I still want to have details about this transaction up to when the white list rule has been triggered

@jptosso, do you remember other considerations behind this comment?
https://github.com/corazawaf/coraza/blob/63a49c8b17230f81a1a812298cbc0c336e59b15f/internal/corazawaf/transaction.go#L905-L908

### CODE REVIEW

**Comment by jptosso** [comment]
It was some difference between modsec 2 and modsec 3 evaluation, but looks good to me.

**Comment by M4tteoP** [comment]
Done! Added them for all the EngineOff checks

**Review by fzipi — APPROVED** [review]
Awesome! Thanks for taking the lead on this one.

**Review by anuraaga — APPROVED** [review]

**Review by jptosso — APPROVED** [review]

**Comment by jcchavezs** [comment]
Thanks for this @M4tteoP. I only have one comment. I'd really like to see the test names to be more descriptive:
`TestProcessRequestHeadersEngineOff` tells me nothing but I am testing Request headers when engine is off but what is expected? from the test I get the expectation is that `LastPhase == 0` but what does that mean exactly? ok no phase has been evaluated because the last phase has never been populated.

So as you can see I need to dig a lot in code and knowledge to realise what the test is testing. Instead I would rather to see `TestProcessRequestHeadersDoesNoEvaluationOnEngineOff`. Does that make sense?

**Pull request merged**
