### PR TITLE
chore: ports interceptor correction

### PR DESCRIPTION
**Pull request by M4tteoP**
Ports from caddy to the reference implementation some @jcchavezs's findings. See: https://github.com/corazawaf/coraza-caddy/pull/107

### CODE REVIEW

**Review by jcchavezs — APPROVED** [review]

**Comment by fzipi** [comment]
@9mlcy7 Sorry, can you translate your thoughts to english?

**Comment by 9mlcy7** [comment]
image
In this case, if it also returns the length of the Write, it may return a short write error in certain situations.

**Comment by jcchavezs** [comment]
@9mlcy7 how is this a problem? if no interception we aim to return the write return values as they are isn't?

**Comment by 9mlcy7** [comment]
@jcchavezs  You're right; the issue occurred because I made some custom modifications to the code.

**Pull request merged**
