### PR TITLE
chore: removes CTL regex.

### PR DESCRIPTION
**Pull request by jcchavezs**
I am not sure why this was added, are supporting key regex? If so it isn't implemented.

Ping @m4tteoP @fzipi 

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**

- [ ] My code includes positive and negative tests.
- [ ] I have an appropriate description with correct grammar.
- [ ] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [ ] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Review by fzipi — COMMENTED** [review]
Let me take a deep look. First thing that looks suspicious, is that we remove something....and no tests are failing.

**Comment by fzipi** [comment]
This should be valid ctl syntax: `ctl:ruleRemoveTargetById=123456;ARGS:/^mycookie_/` (but it doesn't work on ModSecurity: longstanding unfixed issues [#1](https://github.com/SpiderLabs/ModSecurity/issues/717) and [#2](https://github.com/SpiderLabs/ModSecurity/issues/911))

**Comment by jcchavezs** [comment]
Thanks @fzipi. Shall we process with this PR and defer the regex support
until someone request for it?

**Comment by fzipi** [comment]
No, because I was the one requesting it. This was a longstanding thing that makes a difference for our users.

What I see here is, maybe, we are lacking tests to see if this works properly.

Also, which problem are you trying to solve here?

**Comment by jcchavezs** [comment]
Ok, if this is a legit feature we can implement it if you come up with some
tests assertions, what this PR is doing is to clean up the code as that
regex isn't being used anywhere.

**Comment by jcchavezs** [comment]
Also, can we delay this to 3.1?

**Comment by fzipi** [comment]
If you want to remove this, then please create a follow-up issue with all this context and label it for v3.1. And add a dependent PR that reverts (or better, re-adds this) so we can add the relevant tests and complete the feature on top of this.

Please don't remove and forget.

**Comment by jcchavezs** [comment]
I can remove this and link to an issue with the described feature. A revert PR might be overkill as then we will have to do rebases. Also please notice this code I am removing is dead code, it only aims to create a regex once the key is within delimiters and nothing more, no logic, not anything so the value is very low.

**Comment by fzipi** [comment]
Remove whatever you need, create an issue, and tag it 3.1. 

Believe me when I say this feature makes a difference.

**Comment by jcchavezs** [comment]
Created the issue https://github.com/corazawaf/coraza/issues/718

**Review by fzipi — APPROVED** [review]

**Pull request merged**
