### PR TITLE
fix: variable parsing error 

### LINKED ISSUE #1088: ParseVariables function parses regular expressions with escape characters incorrectly
code:
```
func TestParseRule(t *testing.T) {
	tests := []struct {
		name string
		vars string
		want int
	}{
		{"Does not contain escape characters", `ARGS:/(test)/|REQUEST_XML`, 2},
		{"The last variable contains escape characters", `ARGS|REQUEST_XML:/(test)\b/`, 2},
		{"Contains escape characters", `ARGS:/(test\b)/|REQUEST_XML`, 2},
	}

	for _, tc := range tests {
		tt := tc
		t.Run(tt.name, func(t *testing.T) {
			rp := RuleParser{
				rule: corazawaf.NewRule(),
			}
			if err := rp.ParseVariables(tt.vars); err != nil {
				t.Error(err)
			}
			for i := 0; i < reflect.ValueOf(rp.rule).Elem().FieldByName("variables").Len(); i++ {
				fmt.Println(i, reflect.ValueOf(rp.rule).Elem().FieldByName("variables").Index(i).FieldByName("KeyStr").String())
			}
			got := reflect.ValueOf(rp.rule).Elem().FieldByName("variables").Len()
			if got != tt.want {
				t.Error("variables parse error want", tt.want, "got", got)
			}
		})
	}
}
```

output:
```
=== RUN   TestParseRule
=== RUN   TestParseRule/Does_not_contain_escape_characters
0 /(test)/
1 
=== RUN   TestParseRule/The_last_variable_contains_escape_characters
0 
1 /(test)\b/
=== RUN   TestParseRule/Contains_escape_characters
0 /(test\b)/|REQUEST_XM/
    rule_parser_test.go:305: variables parse error want 2 got 1
--- FAIL: TestParseRule (0.00s)
    --- PASS: TestParseRule/Does_not_contain_escape_characters (0.00s)
    --- PASS: TestParseRule/The_last_variable_contains_escape_characters (0.00s)
    --- FAIL: TestParseRule/Contains_escape_characters (0.00s)

```

When my parameter is ARGS:/(test\b)/|REQUEST_XML, I want to get ARGS:/(test\b)/ and REQUEST_XML, but the result is /(test\b)/|REQUEST_XM/

### PR DESCRIPTION
**Pull request by geekeryy**
Fixed the issue that the ParseVariables function would parse the regular expression with escape characters incorrectly

fix #1088

### CODE REVIEW

**Comment by jcchavezs** [comment]
Hi @geekeryy do you mind adding a failing test case for this?

**Comment by fzipi** [comment]
Also, can you link the issue that we are fixing here?

**Comment by jptosso** [comment]
It's impressive that it took almost three years to find this bug 🤣 
Thank you for your contribution

**Comment by jcchavezs** [comment]
Thanks for this. I wonder if we truly need the commented lines. Shall we
remove them?

**Review by fzipi — APPROVED** [review]

**Pull request merged**
