### PR TITLE
Expose AddArgument on tx interface

### PR DESCRIPTION
**Pull request by piyushroshan**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!
Exposing the  AddArgument function allows the control of the arguments evaluated in a transaction.
Especially for custom protocols/library usage where it may not be possible for Coraza to get the raw body to parse. Having the add argument provides a way to add the arguments manually and still retail the behavior.

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v3sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).
- [x] My code is properly linted and passes pre-commit tests.

Thanks for your contribution :heart:

### CODE REVIEW

**Comment by jptosso** [comment]
Shall we use three methods, for get, post, response? Or we could use constants

**Comment by jcchavezs** [comment]
I'd rather have an enum (aka constants) for the first argument and
definitively not call it orig but method or something like that instead.

**Comment by jptosso** [comment]
@piyushroshan could you change the variable name to something like variableName or method? Also transform it into a constant int for get, post, and response.

**Review by jptosso — APPROVED** [review]

**Review by fzipi — APPROVED** [review]
Beautiful

**Pull request merged**
