### PR TITLE
fix: fixes a condition that caused a slice bounds out of range when r…

### PR DESCRIPTION
**Pull request by jcchavezs**
when reading the body buffer.

Closes https://github.com/corazawaf/coraza-caddy/issues/48.

### CODE REVIEW

**Review by M4tteoP — APPROVED** [review]
nice debug!

**Review by anuraaga — COMMENTED** [review]
Can we add a unit test for it?

**Comment by jcchavezs** [comment]
Tricky one. The issue appears to be that position is greater than the
buffer size which not sure how could happen. This is more like a
programmatic double check rather than a use case. Still I might be able to
hardcode some values and make the test if you think it is worth.

**Review by jptosso — APPROVED** [review]

**Comment by anuraaga** [comment]
@jcchavezs Not too sure but if a user could reproduce it then it must need a regression test right?

**Comment by jptosso** [comment]
can we merge this?

**Comment by jcchavezs** [comment]
I need to add a test. Will do that tomorrow.

**Comment by jcchavezs** [comment]
Closing as coraza-caddy should not encounter this but anymore.

**Pull request closed without merging**
