### PR TITLE
Separate out bodybuffer implementation for tinygo that doesn't access…

### LINKED ISSUE #331: Allow using a BodyBuffer not backed by a file for wasm
Currently `BodyBuffer` includes code that writes to a file. This code currently cannot be compiled and used in wasm (even if the code isn't executed) because it will try to import functions for accessing filesystem which don't exist, at least yet. Specifically, it is `os.Remove` that is not available or stubbed.

Unfortunately because this is a code compilation issue, I don't think it would be fixed by having an interface that the code switches based on something like an option, since the code paths would be compiled anyways. Would it be reasonable to have normal and tinygo versions of `BodyBuffer` separated by build tag, with the latter not supporting file storage?

### PR DESCRIPTION
**Pull request by anuraaga**
… filesystem

Fixes #331 

A better technique doesn't come to mind here but happy to hear any ideas on how to improve this. Was able to confirm it works in https://github.com/anuraaga/coraza-wasm-filter/pull/1

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [X] My code includes positive and negative tests.
- [X] I have an appropriate description with correct grammar.
- [X] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Comment by jptosso** [comment]
Is there any reason why we should remove the feature? Could we just create a flag to disable file writing and create a file with constrains to disable file writing?

**Comment by anuraaga** [comment]
@jptosso - I think this does exactly that, or do you mean a flag specific to envoy and not tinygo? I think that currently for this library tinygo=wasm=envoy or similar limited host environment, so I don't think there is a huge benefit to adding a separate flag at least until someone asks.

**Comment by jptosso** [comment]
What about using something like this:

```go
if l >= br.options.MemoryLimit && internal.Tinygo{
```

**Comment by anuraaga** [comment]
If I understand correctly the idea is to maintain multiple files just once for the `TinyGo` flag within internal and use it within bodybuffer or other similar files. I'll give it a try tomorrow.

**Comment by jptosso** [comment]
Thank you, otherwise there could be inconsistencies when we have to create new features or fix bugs

**Comment by anuraaga** [comment]
Thanks @jptosso - tinygo's dead code elimination is working fine, I could confirm this approach works fine in https://github.com/anuraaga/coraza-wasm-filter/pull/1

**Comment by jcchavezs** [comment]
LGTM

**Pull request merged**
