### PR TITLE
Performance optimizations for v2

### PR DESCRIPTION
**Pull request by bxlxx**
Thanks for @anuraaga very much. These are performance optimizations for v2, which based on the @anuraaga's advice.  

> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [x] My code includes positive and negative tests.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Comment by jcchavezs** [comment]
I would really prefer to first merge my revert on `testify` usage and then
`cherry-pick` @anuraaga's commits, otherwise when we rebase v3 on top of V2
original @anuraaga's commits will be skipped and we will lost the history.
Does that sounds good to you?

**Review by jptosso — APPROVED** [review]

**Comment by jcchavezs** [comment]
I merged my revert. Could you please cherry-pick the changes?

**Review by anuraaga — APPROVED** [review]
Thanks!

**Review by jcchavezs — APPROVED** [review]

**Comment by jcchavezs** [comment]
I believe we could cut a release after this merge.

**Pull request merged**
