### PR TITLE
Fix for issue #193

### PR DESCRIPTION
**Pull request by ShiMing-Q**
> Thank you for contributing to Coraza WAF, your effort is greatly appreciated
> Before submitting check if what you want to add to `coraza` list meets [quality standards](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Note**: _that go.mod and go.sum can only be modified for tested dependency updates or justified new features._

**Make sure that you've checked the boxes below before you submit PR:**

- [X] My code includes positive and negative tests.
- [X] I have an appropriate description with correct grammar.
- [X] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/github.com/corazawaf/coraza/v2sso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR :heart:

### CODE REVIEW

**Comment by ShiMing-Q** [comment]
@jptosso Please review this

**Comment by bxlxx** [comment]
> @jptosso Please review this

Thank you for your contribution. Could you fix the code to pass the github action first?

**Comment by ShiMing-Q** [comment]
UT passed, but get another failure

Seems file https://github.com/jptosso/coraza-pcre/blob/master/go.mod is still asking for `github.com/jptosso/coraza-waf/v2`

**Comment by ShiMing-Q** [comment]
@bxlxx Why we got this for compatibility/test?
 
```
go: downloading go.uber.org/multierr v1.8.0
go get: github.com/jptosso/coraza-waf/v2@v2.0.0-rc.3: parsing go.mod:
	module declares its path as: github.com/corazawaf/coraza/v2
	        but was required as: github.com/jptosso/coraza-waf/v2
Error: Process completed with exit code 1.
```

**Comment by bxlxx** [comment]
> @bxlxx Why we got this for compatibility/test?
> 
> ```
> go: downloading go.uber.org/multierr v1.8.0
> go get: github.com/jptosso/coraza-waf/v2@v2.0.0-rc.3: parsing go.mod:
> 	module declares its path as: github.com/corazawaf/coraza/v2
> 	        but was required as: github.com/jptosso/coraza-waf/v2
> Error: Process completed with exit code 1.
> ```

I'm trying to fix the problem. Please wait a moment.

**Comment by ShiMing-Q** [comment]
Not sure if it's due to this file, https://github.com/jptosso/coraza-pcre/blob/master/go.mod
```
# go get -u github.com/jptosso/coraza-pcre@1bea0f0
go: downloading github.com/jptosso/coraza-waf/v2 v2.0.0-rc.3
go: downloading go.uber.org/multierr v1.8.0
go get: github.com/jptosso/coraza-waf/v2@v2.0.0-rc.3: parsing go.mod:
	module declares its path as: github.com/corazawaf/coraza/v2
	        but was required as: github.com/jptosso/coraza-waf/v2
```

**Comment by jptosso** [comment]
> Not sure if it's due to this file, https://github.com/jptosso/coraza-pcre/blob/master/go.mod
> 
> ```
> # go get -u github.com/jptosso/coraza-pcre@1bea0f0
> go: downloading github.com/jptosso/coraza-waf/v2 v2.0.0-rc.3
> go: downloading go.uber.org/multierr v1.8.0
> go get: github.com/jptosso/coraza-waf/v2@v2.0.0-rc.3: parsing go.mod:
> 	module declares its path as: github.com/corazawaf/coraza/v2
> 	        but was required as: github.com/jptosso/coraza-waf/v2
> ```

It seems you are right, that's because I have created a tag for the renamed project. I will fix it

**Comment by fzipi** [comment]
What needs to be done here? Do we need to rebase also, right?

**Comment by jptosso** [comment]
It is a valid solution and it's passing tests but I think we should discuss this one.

Maybe adding the parent ID as a parameter is too much and we could add the parent rule id to MatchedData

**Comment by ShiMing-Q** [comment]
> It is a valid solution and it's passing tests but I think we should discuss this one.
> 
> Maybe adding the parent ID as a parameter is too much and we could add the parent rule id to MatchedData

Sounds good, let me check the code again.

**Review by fzipi — APPROVED** [review]
Looking good now.

**Comment by fzipi** [comment]
What is needed here now? Can we document what's the actual state?

**Comment by jptosso** [comment]
So the issue reporter said it's wrong but we haven't received the detailed feedback. I will try to get it today.

**Comment by jptosso** [comment]
Please review #216

**Comment by jptosso** [comment]
Closed in favor of #220

Thank you Shiming, your PR was technically right but exporting new fields is a sensitive topic and we should avoid it if possible. Also tests were required.

**Pull request closed without merging**
