### PR TITLE
chore: drops Transaction.ProcessRequest into an own package.

### PR DESCRIPTION
**Pull request by jcchavezs**
This PR follows from #283

Ping @jptosso

### CODE REVIEW

**Comment by fzipi** [comment]
There's plenty of annotations in the tests. Cen you fix them?

**Comment by jcchavezs** [comment]
Just fixed it @fzipi

**Comment by fzipi** [comment]
There is a proposal in the original issue about moving it to `coraza/v3/utils/http`. Do we still think that is a good naming? @jptosso ?

**Comment by jcchavezs** [comment]
I don't like quite much the "utils" concept. I think the http package is
good enough do you still think we should do the utils prefix?

**Review by jptosso — APPROVED** [review]
LGTM

**Pull request merged**
